name: CI/CD Pipeline - Calculadora IMC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Atualize para v22.x

      - name: Instalar dependências
        run: npm install

      - name: Rodar os testes
        run: npm test

      - name: Build do projeto
        run: npm run build

  # Job de Teste
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Rodar os testes
        run: npm test

  # Job de Deploy (opcional)
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Deploy
        run: |
          echo "Realizando deploy para produção"
